class SagaStateEnum:
    INITIATED = "INITIATED"
    STARTED = "SAGA_STARTED"
    ORDER_LOCKED = "ORDER_LOCKED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    STOCK_PENDING = "STOCK_PENDING"
    STOCK_COMPLETED = "STOCK_COMPLETED"
    STOCK_REMOVED = "STOCK_REMOVED"
    ORDER_LOCK_RELEASED = "ORDER_LOCK_RELEASED"
    ORDER_FINALIZED = "ORDER_FINALIZED"
    COMPENSATING_PAYMENT = "COMPENSATING_PAYMENT"
    PAYMENT_COMPENSATED = "PAYMENT_COMPENSATED"
    COMPENSATING_STOCK = "COMPENSATING_STOCK"
    STOCK_COMPENSATED = "STOCK_COMPENSATED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    STOCK_FAILED = "STOCK_FAILED"
    ORDER_LOCK_RELEASE_FAILED = "ORDER_LOCK_RELEASE_FAILED"
    SAGA_FAILED = "SAGA_FAILED"
    SAGA_FAILED_INITIALIZATION = "SAGA_FAILED_INITIALIZATION"
    SAGA_FAILED_ORDER_NOT_FOUND = "SAGA_FAILED_ORDER_NOT_FOUND"
    SAGA_FAILED_RECOVERY = "SAGA_FAILED_RECOVERY"
    ORDER_FINALIZATION_FAILED = "ORDER_FINALIZATION_FAILED"
    STOCK_RESERVATION_FAILED = "STOCK_RESERVATION_FAILED"
    PAYMENT_INITIATION_FAILED = "PAYMENT_INITIATION_FAILED"
    SAGA_COMPLETED = "SAGA_COMPLETED"
    ORDER_MODIFIED = "ORDER_MODIFIED"

TERMINAL_SAGA_STATES = {
    SagaStateEnum.SAGA_COMPLETED,
    SagaStateEnum.ORDER_FINALIZED,
    SagaStateEnum.SAGA_FAILED,
    SagaStateEnum.SAGA_FAILED_INITIALIZATION,
    SagaStateEnum.SAGA_FAILED_ORDER_NOT_FOUND,
    SagaStateEnum.SAGA_FAILED_RECOVERY,
    SagaStateEnum.ORDER_FINALIZATION_FAILED,
    SagaStateEnum.STOCK_RESERVATION_FAILED,
    SagaStateEnum.PAYMENT_FAILED,
    SagaStateEnum.STOCK_FAILED,
    SagaStateEnum.PAYMENT_INITIATION_FAILED
}

