version: "3"

networks:
  redis-cluster-network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - redis-cluster-network

  gateway:
    build: ./gateway
    command: hypercorn app -b 0.0.0.0:5000
    environment:
      AMQP_URL: "amqp://user:password@rabbitmq:5672/"
    ports:
      - "8080:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - redis-cluster-network

  # ------------------------- Redis Sentinel Cluster ----------------------------
  redis-sentinel-1:
    image: redis:7.2-bookworm
    container_name: redis-sentinel-1
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./redis/sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-order-master
      - redis-payment-master
      - redis-stock-master
    ports:
      - "26379:26379"
    networks:
      - redis-cluster-network

  redis-sentinel-2:
    image: redis:7.2-bookworm
    container_name: redis-sentinel-2
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./redis/sentinel.conf:/etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    networks:
      - redis-cluster-network
    depends_on:
      - redis-sentinel-1

  redis-sentinel-3:
    image: redis:7.2-bookworm
    container_name: redis-sentinel-3
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./redis/sentinel.conf:/etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    networks:
      - redis-cluster-network
    depends_on:
      - redis-sentinel-1

  # ------------------------- Redis Master-Replica for Order Service ----------
  redis-order-master:
    image: redis:7.2-bookworm
    container_name: redis-order-master
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis"]
    ports:
      - "6379:6379"
    networks:
      - redis-cluster-network

  redis-order-replica-1:
    image: redis:7.2-bookworm
    container_name: redis-order-replica-1
    command: ["redis-server", "--replicaof", "redis-order-master", "6379", "--masterauth", "redis", "--requirepass", "redis"]
    networks:
      - redis-cluster-network
    depends_on:
      - redis-order-master

  redis-order-replica-2:
    image: redis:7.2-bookworm
    container_name: redis-order-replica-2
    command: ["redis-server", "--replicaof", "redis-order-master", "6379", "--masterauth", "redis", "--requirepass", "redis"]
    networks:
      - redis-cluster-network
    depends_on:
      - redis-order-master

  # ------------------------- Redis Master-Replica for Stock Service ----------
  redis-stock-master:
    image: redis:7.2-bookworm
    container_name: redis-stock-master
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis"]
    ports:
      - "6380:6379"
    networks:
      - redis-cluster-network

  redis-stock-replica-1:
    image: redis:7.2-bookworm
    container_name: redis-stock-replica-1
    command: ["redis-server", "--replicaof", "redis-stock-master", "6379", "--masterauth", "redis", "--requirepass", "redis"]
    networks:
      - redis-cluster-network
    depends_on:
      - redis-stock-master

  redis-stock-replica-2:
    image: redis:7.2-bookworm
    container_name: redis-stock-replica-2
    command: ["redis-server", "--replicaof", "redis-stock-master", "6379", "--masterauth", "redis", "--requirepass", "redis"]
    networks:
      - redis-cluster-network
    depends_on:
      - redis-stock-master

  # ------------------------- Redis Master-Replica for Payment Service --------
  redis-payment-master:
    image: redis:7.2-bookworm
    container_name: redis-payment-master
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis"]
    ports:
      - "6381:6379"
    networks:
      - redis-cluster-network

  redis-payment-replica-1:
    image: redis:7.2-bookworm
    container_name: redis-payment-replica-1
    command: ["redis-server", "--replicaof", "redis-payment-master", "6379", "--masterauth", "redis", "--requirepass", "redis"]
    networks:
      - redis-cluster-network
    depends_on:
      - redis-payment-master

  redis-payment-replica-2:
    image: redis:7.2-bookworm
    container_name: redis-payment-replica-2
    command: ["redis-server", "--replicaof", "redis-payment-master", "6379", "--masterauth", "redis", "--requirepass", "redis"]
    networks:
      - redis-cluster-network
    depends_on:
      - redis-payment-master

  # ------------------------- Order Service -----------------------------------
  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:5000
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    networks:
      - redis-cluster-network
    depends_on:
      - redis-order-master
      - redis-sentinel-1
      - rabbitmq

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    networks:
      - redis-cluster-network
    depends_on:
      - redis-stock-master
      - redis-sentinel-1
      - rabbitmq

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: payment:latest
    volumes:
      - ./common:/usr/src/app/payment/common
    environment:
      AMQP_URL: "amqp://user:password@rabbitmq:5672/"
    env_file:
      - env/payment_redis.env
    networks:
      - redis-cluster-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis-payment-master:
        condition: service_started
